In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv("homeprices.csv")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [4]:
model.coef_

array([135.78767123])

In [5]:
model.intercept_

180616.43835616432

In [7]:
model.predict([[3000]])

array([587979.45205479])

In [8]:
#With Pickle
import pickle

In [9]:
with open('my_model_pickle','wb') as file:
    pickle.dump(model,file)

In [11]:
with open('my_model_pickle','rb') as file:
    mmp = pickle.load(file)

In [12]:
mmp.coef_

array([135.78767123])

In [13]:
mmp.intercept_

180616.43835616432

In [14]:
mmp.predict([[3000]])

array([587979.45205479])

In [17]:
import joblib


In [18]:
joblib.dump(model, 'my_model_joblib')

['my_model_joblib']

In [21]:
mmjl = joblib.load('my_model_joblib')

In [22]:
mmjl.coef_


array([135.78767123])

In [23]:
mmjl.intercept_

180616.43835616432

In [24]:
mmjl.predict([[3000]])

array([587979.45205479])