In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [3]:
df=pd.read_csv("homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [6]:
##Nan Variables
import math
median_bedrooms=math.floor(df.bedrooms.median())

In [7]:
median_bedrooms

4

In [11]:
df['bedrooms']=df['bedrooms'].fillna(median_bedrooms, inplace = True)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [13]:
reg=linear_model.LinearRegression()
reg.fit(df.drop('price',axis='columns'),df.price)

LinearRegression()

In [14]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [16]:
reg.intercept_

221323.00186540408

In [18]:
reg.predict([[3000,3,40]])

array([498408.25158031])

# 2. Example

In [20]:
df2=pd.read_csv("hiring.csv")
df2

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [22]:
from word2number import w2n

In [24]:
df2['experience'].fillna("zero",inplace=True)
df2

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [25]:
df2['experience']=df2['experience'].apply(w2n.word_to_num)
df2

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [27]:
import math
median_test_score = math.floor(df2['test_score(out of 10)'].mean())
median_test_score

7

In [28]:
df2['test_score(out of 10)'] = df2['test_score(out of 10)'].fillna(median_test_score)
df2

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [30]:
reg = linear_model.LinearRegression()
reg.fit(df2[['experience','test_score(out of 10)','interview_score(out of 10)']],df2['salary($)'])

LinearRegression()

In [33]:
reg.predict([[0,3,3]])

array([28099.02644456])

In [32]:
reg.predict([[12,10,10]])

array([93747.79628651])

In [34]:
reg.predict([[9,5,5]])

array([63137.03091166])